# Strip the 'v' from the version tag
{% raw %}
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}
{% endraw %}

package:
  name: lima-camera-{{cookiecutter.project_name}}-tango
  version: {{ "{{ version }}" }}

source:
  path: ../..

build:
  number: {{ "{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}" }}
  noarch: python

requirements:
  build:
    - ninja
    - cmake
    - lima-core
  run:
    - lima-tango-server
    - lima-camera-{{cookiecutter.project_name}}

test:
  source_files:
    - test
  requires:
    - pytest
  commands:
    - pytest test/test_tango.py

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
