############################################################################
# This file is part of LImA, a Library for Image Acquisition
#
# Copyright (C) : 2009-2025
# European Synchrotron Radiation Facility
# CS40220 38043 Grenoble Cedex 9 
# FRANCE
# Contact: lima@esrf.fr
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
############################################################################
#=============================================================================
#
# file :        {{cookiecutter.project_name}}.py
#
# description : Python source for the {{cookiecutter.project_name}} and its commands.
#                The class is derived from Device. It represents the
#                CORBA servant object which will be accessed from the
#                network. All commands which can be executed on the
#                {{cookiecutter.project_name}} are implemented in this file.
#
# project :     TANGO Device Server
#
# copyleft :    European Synchrotron Radiation Facility
#               BP 220, Grenoble 38043
#               FRANCE
#
#=============================================================================
#          This file is generated by POGO
#    (Program Obviously used to Generate tango Object)
#
#         (c) - Software Engineering Group - ESRF
#=============================================================================
#

import PyTango
import sys

from Lima import Core

#==================================================================
#   {{cookiecutter.project_name}} Class Description:
#
#
#==================================================================


class {{cookiecutter.project_name}}(PyTango.LatestDeviceImpl):

#--------- Add you global variables here --------------------------
    Core.DEB_CLASS(Core.DebModApplication, 'LimaCCDs')

#------------------------------------------------------------------
#    Device constructor
#------------------------------------------------------------------
    def __init__(self,cl, name):
        PyTango.LatestDeviceImpl.__init__(self,cl,name)

        self.init_device()


#------------------------------------------------------------------
#    Device destructor
#------------------------------------------------------------------
    def delete_device(self):
        pass


#------------------------------------------------------------------
#    Device initialization
#------------------------------------------------------------------
    def init_device(self):
        self.set_state(PyTango.DevState.ON)
        self.get_device_properties(self.get_device_class())


#==================================================================
#
#    {{cookiecutter.project_name}}Class class definition
#
#==================================================================
class {{cookiecutter.project_name}}Class(PyTango.DeviceClass):

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        }


#------------------------------------------------------------------
#    {{cookiecutter.project_name}}Class Constructor
#------------------------------------------------------------------
    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type(name)

#----------------------------------------------------------------------------
# Plugins
#----------------------------------------------------------------------------
from Lima import {{cookiecutter.project_name}} as {{cookiecutter.project_name}}Acq

_{{cookiecutter.project_name}}Interface = None
_{{cookiecutter.project_name}}Camera = None

def get_control(**keys) :
    global _{{cookiecutter.project_name}}Interface
    global _{{cookiecutter.project_name}}Camera
    if _{{cookiecutter.project_name}}Interface is None:
        _{{cookiecutter.project_name}}Camera = {{cookiecutter.project_name}}Acq.Camera()
        _{{cookiecutter.project_name}}Interface = {{cookiecutter.project_name}}Acq.Interface(_{{cookiecutter.project_name}}Camera)
    return Core.CtControl(_{{cookiecutter.project_name}}Interface)

def get_tango_specific_class_n_device() :
    return {{cookiecutter.project_name}}Class,{{cookiecutter.project_name}}


